version: '3.7'

services:
    mumble-web:
        image: mumble-web:latest
        networks:
          mumble-net:
            aliases:
              - web
    mumble-web-proxy:
        image: web-proxy:latest
        ports:
          - "64737:64737"
        networks:
          mumble-net:
            aliases:
              - proxy
    mumble-server:
        image: mumble:latest
        ports:
          - "50051:50051"
          - "64738:64738"
        volumes:
          - /opt/mumble/murmur:/etc/murmur:ro
        networks:
          mumble-net:
            aliases:
              - mumble
    nginx:
        image: nginx:latest
        ports:
          - "80:80"
          - "443:443"
        volumes:
          - /opt/mumble/nginx.conf:/etc/nginx/conf.d/mumble.conf
          - /etc/letsencrypt:/etc/letsencrypt:ro
        networks:
          - mumble-net

networks:
    mumble-net:
