version: '3.7'

services:
    mumble-web:
        container_name: mumble-web
        image: mumble-web:latest
        networks:
          mumble-net:
            aliases:
              - web
    mumble-web-proxy:
        container_name: mumble-web-proxy
        image: web-proxy:latest
        ports:
          - "64737:64737"
        networks:
          mumble-net:
            aliases:
              - proxy
    mumble-server:
        container_name: mumble-server
        image: mumble:latest
        ports:
          - "50051:50051"
          - "64738:64738"
        volumes:
          - /opt/mumble/fullchain.pem:/etc/mumble/fullchain.pem:ro
          - /opt/mumble/privkey.pem:/etc/mumble/privkey.pem:ro
          - /opt/mumble/murmur.ini:/etc/murmur/murmur.ini:ro
        networks:
          mumble-net:
            aliases:
              - mumble
    nginx:
        container_name: nginx
        image: nginx:latest
        ports:
          - "80:80"
          - "443:443"
        volumes:
          - /opt/mumble/nginx.conf:/etc/nginx/conf.d/mumble.conf
          - /opt/mumble/fullchain.pem:/etc/mumble/fullchain.pem:ro
          - /opt/mumble/privkey.pem:/etc/mumble/privkey.pem:ro
          - /opt/wordpress/fullchain.pem:/etc/wordpress/fullchain.pem:ro
          - /opt/wordpress/privkey.pem:/etc/wordpress/privkey.pem:ro
        networks:
          wp-net:
            aliases:
              - nginx
          mumble-net:
            aliases:
              - nginx
        depends_on:
          - mumble-web
          - mumble-web-proxy
    botamusique:
        container_name: mumble-music
        image: botamusique:latest
        volumes:
          - /opt/mumble/botamusique.ini:/etc/botamusique.ini
        networks:
          mumble-net:
            aliases:
              - musicbot
        depends_on:
          - mumble-server


networks:
    mumble-net:
      name: mumble-net
    wp-net:
      name: wp-net
