version: '3.7'

services:
    mumble-web:
        image: mumble-web:latest
    mumble-web-proxy:
        image: web-proxy:latest
        links:
          - "mumble-server:mumble"
    mumble-server:
        image: mumble:latest
        ports:
          - "64737:64737"
          - "64738:64738"
        volumes:
          - /opt/murmur/murmer.ini:/etc/murmur/murmur.ini:ro
          - /etc/letsencrypt:/etc/letsencrypt:ro
    nginx:
        image: nginx:latest
        ports:
          - "80:80"
          - "443:443"
        volumes:
          - /opt/mumble/nginx.conf:/etc/nginx/conf.d/mumble.conf
          - /etc/letsencrypt:/etc/letsencrypt:ro
        links:
          - "mumble-web:web"
          - "mumble-web-proxy:proxy"
